version: "3.8"
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: semitechnologies/weaviate:1.24.0 # Use a stable version
    ports:
      - "8080:8080"
      - "50051:50051" # For gRPC
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none" # We will provide our own embeddings from Ollama
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: "node1"
